const Data=[
    {id:1,
    title:'buttermilkpancakes',
    category:'breakfast',
    price:15.99,
    img:'https://simplyhomecooked.com/wp-content/uploads/2022/08/buttermilk-pancakes-2.jpg',
    desc:`I'mbabywokemlkshkwolfb itterslive-edgebluebot tle,hammockfreegancoppermugwhatevercold-pressed`,},
    {id:2,
    title:'dinerdouble',
    category:'lunch',
    price:13.99,
    img:'https://d1dxs113ar9ebd.cloudfront.net/225batonrouge/2021/06/20210521-ACS_7346.jpg',
    desc:`vaporwareiPhonemumblecores elvagerawdenimslow-carbleggingsgochujang helveticamanbraidjianbing.Marfathundercats`,},
    {id:3,
    title:'godzillamilkshake',
    category:'shakes',
    price:6.99,img:'https://media-cdn.tripadvisor.com/media/photo-m/1280/1c/c2/29/eb/milo-godzilla.jpg',desc:`ombuchachillwa vefannypac k3wolfmoonst reetartphotoboothbeforetheysoldoutorganicviral.`,},
    {id:4,
    title:'countrydelight',
    category:'breakfast',
    price:20.99,img:'https://assets.entrepreneur.com/content/3x2/2000/1606136871-breakfast.jpg',
    desc:`Shabbychickeffiyehneutrasna ckwaveporkbellyshoreditch.Prismaustin mlkshktruffaut,`,},
    {id:5,
    title:'eggattack',
    category:'lunch',
    price:22.99,img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRaiMqf0071ckSTKB6EGTiWV00PXLJu0yri-e0SrxVxgRXP3Z72i_Orh1qM181qOK5fxx4&usqp=CAU',desc:`franzenvega
    npabstbicyclerightskickstarterpinter estmeditationf arm-to-table90'spop-up`,},
    {id:6,
    title:'oreodream',
    category:'shakes',
    price:18.99,
    img:'https://www.julieseatsandtreats.com/wp-content/uploads/2012/09/Oreo-Dream-Salad-Main.jpg',
    desc:`Portlandchicharroneset hicaledisonbulb,palos antocraftbeerchiaheirloomiPhoneeveryday`,},
    {id:7,
    title:'baconoverflow',
    category:'breakfast',
    price:8.99,img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzoCD5RiCtEViaHkPMjqW-H_HLeGIEA5FIAiWRcHsAr1deiGsWV5ddbUTNwt_xxzs6bhs&usqp=CAU',
    desc:`carryjianbingnormcorefreegan.Vi ralsingle-origincoffeelive-edge,porkbellycloudbreadicelandputabird`,},
    {id:8,
    title:'americanclassic',
    category:'lunch',
    price:12.99,img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-hCT_KzkAB9FdPPGBuITUYR3EH71MDjWfmA&usqp=CAU',desc:`onittumblrki ckstarterthundercats migaseverydaycarrysquidpalosantoleggings.Foodtrucktruffaut`,},
    {id:9,
    title:'quarantinebuddy',
    category:'shakes',
    price:16.99,img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQQ5XmedIf_r6QGu4vUp0F0jZCImsYHIcpzg&usqp=CAU',
    desc:`skateboardfamsynthaut hentics emiotics.Live-edgelyftaf,edisonbulbyucciecrucifixmicrodosing.`,},]

    export default Data;